project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!*hide*.qmd"
  resources: 
    - "*.pdf"

execute:
  freeze: auto  # re-render only when source changes

toc: true
#number-sections: true
#bibliography: references.bib  


website:
  title: "Programação"
  navbar:
    left:
      - href: index.qmd
        text: Home

format: 
  html:
    toc: true
    toc-depth: 3
    code-fold: true
    html-math-method: katex
    embed-resources: true
#    css: styles.css
#  pdf:
#    documentclass: report
#    margin-left: 30mm
#    margin-right: 30mm

